#!/bin/bash

function get_name {
  local name=""
  local pattern="$1"
  local count

  for (( i=0; i<${#pattern}; i++ )); do
    token=${pattern:$i:1}

    [[ $i -eq 0 ]] && count="$2" || count=1

    for (( j=0; j<$count; j++ )); do
      name+=$token
    done
    
  done

  echo "$name"
}

folder_pattern=$3
file_name_pattern=$(echo "$5" | awk -F "." '{print $1}')
file_extension_pattern=$(echo "$5" | awk -F "." '{print $2}')
size=$(df / | tail -n 1 | awk '{print $4}')
date=$(date +"%d%m%y")

counter_d=4
for (( k=0; k<$2; k++ )); do
  folder_path=$(get_name "$folder_pattern" "$counter_d")
  folder_path="${1}${folder_path}_${date}/"
  mkdir "$folder_path"
  echo "folder;$folder_path;$date" >> logfile

  counter_f=4
  for (( l=0; l<$4; l++ )); do
    file_name=$(get_name "$file_name_pattern" "$counter_f")
    file_extension=$file_extension_pattern
    file_path="${folder_path}${file_name}.${file_extension}_${date}"
    if [[ $size -gt 1048576 ]]; then
      file_size=$6
      fallocate -l "$file_size" "$file_path"
    else
      echo "Can't create $file_path: disk free space is less than 1G"
      exit 0
    fi
    echo "file;$file_path;$date;$6" >> logfile
    (( counter_f++ ))
  done
  (( counter_d++ ))
done
