#!/bin/bash

function get_entry {
  # IP
  out_ip=$(($RANDOM % 255 + 1)).$(($RANDOM % 256)).$(($RANDOM % 256)).$(($RANDOM % 256))
  # Response codes
  status_codes=('200' '201' '400' '401' '403' '404' '500' '501' '502' '503')
  code_index=$(( $RANDOM % ${#status_codes[@]} ))
  out_code="${status_codes[$code_index]}"
  # Methods
  methods=('GET' 'POST' 'PUT' 'PATCH' 'DELETE')
  method_index=$(( $RANDOM % ${#methods[@]} ))
  out_method="${methods[$method_index]}"
  # Dates
  # today=$(date +"%Y-%m-%d")
  today="2022-01-01"
  out_date=$(date --date="${today} +$1 day +$2 minute" +'%d/%b/%Y:%T %z')
  # Agent request URL
  urls=('https://google.com' 'https://yandex.ru' 'https://nasa.com' 'https://rambler.com' 'https://yahoo.com' 'https://vk.com' 'https://ok.com')
  url_index=$(( $RANDOM % ${#urls[@]} ))
  out_url="${urls[$url_index]}"
  # Agents
  agents=('Mozilla' 'Google Chrome' 'Opera' 'Safari' 'Internet Explorer' 'Microsoft Edge' 'Crawler and bot' 'Library and net tool')
  agent_index=$(( $RANDOM % ${#agents[@]} ))
  out_agent="${agents[$agent_index]}"

  echo "${out_ip} - - [${out_date}] \"${out_method} ${out_url}\" ${out_code} $(($RANDOM % 5000 + 1)) \"-\" \"$out_agent\""
}

for (( i=1; i<=5; i++ )); do
  count=$(($RANDOM % 1000 + 1))
  filename="logfile${i}"

  for (( j=1; j<=$count; j++ )); do
    get_entry "$i" "$j" >> "$filename"
  done
done

# Status codes

# 1xx Informational

# 100	Continue
# 101	Switching protocols
# 102	Processing
# 103	Early Hints
 	 
# 2xx Succesful

# 200	OK
# 201	Created
# 202	Accepted
# 203 	Non-Authoritative Information
# 204	No Content
# 205	Reset Content
# 206	Partial Content
# 207	Multi-Status
# 208	Already Reported
# 226	IM Used
 	 
# 3xx Redirection

# 300	Multiple Choices
# 301	Moved Permanently
# 302	Found (Previously "Moved Temporarily")
# 303	See Other
# 304	Not Modified
# 305	Use Proxy
# 306	Switch Proxy
# 307	Temporary Redirect
# 308	Permanent Redirect
 	 
# 4xx Client Error

# 400	Bad Request
# 401	Unauthorized
# 402	Payment Required
# 403	Forbidden
# 404	Not Found
# 405	Method Not Allowed
# 406	Not Acceptable
# 407	Proxy Authentication Required
# 408	Request Timeout
# 409	Conflict
# 410	Gone
# 411	Length Required
# 412	Precondition Failed
# 413	Payload Too Large
# 414	URI Too Long
# 415	Unsupported Media Type
# 416	Range Not Satisfiable
# 417	Expectation Failed
# 418	I'm a Teapot
# 421	Misdirected Request
# 422	Unprocessable Entity
# 423	Locked
# 424	Failed Dependency
# 425	Too Early
# 426	Upgrade Required
# 428	Precondition Required
# 429	Too Many Requests
# 431	Request Header Fields Too Large
# 451	Unavailable For Legal Reasons
 	 
# 5xx Server Error

# 500	Internal Server Error
# 501	Not Implemented
# 502	Bad Gateway
# 503	Service Unavailable
# 504	Gateway Timeout
# 505	HTTP Version Not Supported
# 506	Variant Also Negotiates
# 507	Insufficient Storage
# 508	Loop Detected
# 510	Not Extended
# 511	Network Authentication Required
